services:
  shopper_be:
    container_name: shopper_be
    build:
      context: ./shopper-be
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - shopper_db
    volumes:
      - ./shopper-be:/var/www/html
    networks:
      - app_network

  shopper_db:
    container_name: shopper_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopper_db
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app_network

networks:
  app_network:
    driver: bridge