services:
  shopper_be:
    container_name: shopper_be
    build:
      context: ./shopper-be
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - shopper_db
    environment:
      DB_CONNECTION: mysql
      DB_USERNAME: root
      DB_HOST: shopper_db
      DB_PORT: 3306
      DB_PASSWORD: password
      DB_DATABASE: shopper_db
    volumes:
      - ./shopper-be:/var/www/html
    networks:
      - app_network

  shopper_db:
    container_name: shopper_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopper_db
    ports:
      - "3307:3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge