name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:stable
        options: --privileged
        ports:
          - 8000:80
          - 3307:3306

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create environment files
        run: |
          cp ./shopper-be/.env.example ./shopper-be/.env

      - name: Build and run Docker Compose
        run: |
          docker compose -f docker-compose.prod.yml up -d
          sleep 30 # adjust time as needed for containers to start

      - name: Check containers are up and running
        run: docker ps -a

  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Composer install
        run: docker compose exec shopper_be composer install

  migrate:
    name: Run Migrations
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Laravel migrations
        run: |
          docker compose exec shopper_be php artisan migrate --force
          docker compose exec shopper_be php artisan db:seed

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: migrate

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Laravel tests
        run: docker compose exec shopper_be php artisan test
